# Generated by Django 4.2 on 2023-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userValidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadharcandidate',
            name='validationRequired',
            field=models.BooleanField(default=False),
        ),
    ]
